// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type NewTodo struct {
	Text string `json:"text"`
}

type Notification struct {
	EventCode string    `json:"eventCode"`
	CreatedAt time.Time `json:"createdAt"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type UpdateTodo struct {
	ID   string `json:"id"`
	Done bool   `json:"done"`
	Text string `json:"text"`
}
